In [14]:
# 1或2 不能连续两次2
# 最后一位为1的情况f(n-1)
# 最后一位为2的情况f(n-3)
# f(n) = f(n-1) + f(n-3)
def eat(m):
    if m < 5:
        return m
    f = [0] * (m+1)
    print(f)
    for i in range(5):
        f[i] = i
    print(f)
    for i in range(5,m+1):
        f[i] = f[i-1] + f[i-3]
    print(f)
    return f[-1]
eat(6)

[0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 0, 0]
[0, 1, 2, 3, 4, 6, 9]


9

In [17]:
# 1或2 2后两位必须两个1（211）
# 最后一位为1的情况f(n-1)
# 最后一位为2的情况f(n-4)
# f(n) = f(n-1) + f(n-3)
def eat(n):
    if n < 6:
        return n
    f = [0] * (n+1)
    print(f)
    for i in range(5):
        f[i] = i
    print(f)
    for i in range(5,n+1):
        f[i] = f[i-1] + f[i-4]
    print(f)
    return f[-1]
eat(20)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 1, 2, 3, 4, 5, 7, 10, 14, 19, 26, 36, 50, 69, 95, 131, 181, 250, 345, 476, 657]


657

In [39]:
# 每次只能向下或者向右移动一步
# dp[i] [j] = dp[i-1] [j] + dp[i] [j-1]
# dp[0] [0….n-1] = 1; // 相当于最上面一行，机器人只能一直往右走
# dp[0…m-1] [0] = 1; // 相当于最左面一列，机器人只能一直往下走
def route(m,n):
    if(m<0 or n <0):
        return 0
#     r = [[1 for _ in range(n)] for _ in range(m)]
    r = np.ones((m, n), dtype=int)
    print(r)
#     for i in range(m):
#         r[i][0] = 1
#     for i in range(n):
#         r[0][i] = 1
    for k in range(1,m):
         for j in range(1,n):
                r[k][j] = r[k-1][j] + r[k][j-1]
    print(r)
    return r[m-1][n-1]

route(3,5)  

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[ 1  1  1  1  1]
 [ 1  2  3  4  5]
 [ 1  3  6 10 15]]


15

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

0