In [2]:
import torch

In [3]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5., 6], 
                   [7, 8], 
                   [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

张量可以具有任意数量的维度，并且沿着每个维度具有不同的长度。我们可以使用张量的.shape性质来检查沿每个维度的长度。

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [12]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

创建了3个张量x，w和b，都是数字。w和b有一个附加参数requires_grad设置为True

In [13]:
# 算术运算
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

y是一个张量，其值为3*4+5=17。可以自动计算y的导数w.r.t.，即requires_grad设置为True的张量，即w和b。要计算导数，可以对结果y调用向后方法

In [14]:
# 计算导数
y.backward()

y相对于输入张量的导数存储在相应张量的.grad属性中

In [15]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


dy/dw具有与x相同的值，即3，
并且dy/db具有值1。
x.grad为None，因为x没有将requires_grad设置为True。

w.grad中的“grad”代表梯度

In [16]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

使用torch.from_Numpy将Numpy数组转换为PyTorch张量

In [17]:
# 将numpy数组转换为torch张量
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [18]:
#numpy数组和torch张量是否具有类似的数据类型
x.dtype, y.dtype

(dtype('float64'), torch.float64)

可以使用张量的“.Numpy”方法将PyTorch张量转换为Numpy数组

In [19]:
#将torch张量转换为numpy数组
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

# model

In [1]:
import torch
from torch import optim
import torch.nn as nn
import torch.nn.functional as F
import numpy as np


In [ ]:
def get_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = Network_NN().to(device)

    return model, optim.SGD(model, parameters(), lr=0.001)

def loss_batch(model, loss_func, inputs, labels, opt=None):
    loss = loss_func(model(inputs), labels)
    if opt is not None:
        loss.backward()
        opt.step()
        opt.zero_grad
        
    return loss.item(),len(inputs)

In [ ]:
def fit(epochs, model, loss_func, opt, train_dl, valid_dl):
    for epoch in range(epochs):
        model.train()
        for inputs,labels in train_dl:
            inputs,labels=inputs.to(device),labels.to(device) #GPU
            loss_batch(model, loss_func, inputs, labels, opt)
        
        model.eval()
        with torch.no_grad():
            losses,nums = zip(*[loss_batch(model, loss_func, inputs.to(device), labels.to(device)) for inputs,labels in valid_dl])
            val_loss = np.sum(np.multiply(loss, nums))/np.sum(nums)
            print('当前epoch: ' + str(epochi), '验证集损失：' + str(val_loss))

In [ ]:
class Network_NN(nn.Module):
    def __init__(self):
        super(Network_NN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return x

In [ ]:
train_dl, valid_dl = get_data(train_ds, valid_ds, bs)
model, opt = get_model()
# 分类问题常用的损失函数
loss_func = nn.CrossEntropyLoss()
fit(100, model, loss_func, opt, train_dl, valid_l)