In [1]:
import pandas as pd
import numpy as np

In [42]:
df= pd.DataFrame({'A':[1,2],'B':[[3,4],[5,6]],'C':[[7,8],[9,0]]})
df

A       B       C
0  1  [3, 4]  [7, 8]
1  2  [5, 6]  [9, 0]

In [43]:
df.A.repeat(df.B.str.len())

0    1
0    1
1    2
1    2
Name: A, dtype: int64

In [44]:
df.B.values

array([list([3, 4]), list([5, 6])], dtype=object)

In [45]:
np.concatenate(df.B.values)

array([3, 4, 5, 6])

In [46]:
result = pd.DataFrame({'A':df.A.repeat(df.B.str.len()),
                       'B':np.concatenate(df.B.values),
                    'C':np.concatenate(df.C.values),
                      })
result

A  B  C
0  1  3  7
0  1  4  8
1  2  5  9
1  2  6  0

In [53]:
df

A       B       C
0  1  [3, 4]  [7, 8]
1  2  [5, 6]  [9, 0]

In [52]:
df.append(df)

A       B       C
0  1  [3, 4]  [7, 8]
1  2  [5, 6]  [9, 0]
0  1  [3, 4]  [7, 8]
1  2  [5, 6]  [9, 0]

In [70]:
np.repeat(df.A.values,list(map(len,df.B.values)))

array([1, 1, 2, 2], dtype=int64)

In [59]:
np.concatenate(df.B.values)

array([3, 4, 5, 6])

In [60]:
np.concatenate(df.C.values)

array([7, 8, 9, 0])

In [68]:
new_result = np.dstack((np.repeat(df.A.values,list(map(len,df.B.values))),np.concatenate(df.B.values),np.concatenate(df.C.values)))
new_result

array([[[1, 3, 7],
        [1, 4, 8],
        [2, 5, 9],
        [2, 6, 0]]], dtype=int64)

In [67]:
pd.DataFrame(data=new_result[0],columns=df.columns)

A  B  C
0  1  3  7
1  1  4  8
2  2  5  9
3  2  6  0